### ISSUE TITLE
Create Model Layer

### ISSUE THREAD

**Issue by schirrel** [schirrel/pg-connection#2]
as in https://github.com/schirrel/node-simple-skeleton/tree/master/src/database/models

**Comment by Aniruddha-Shriwant** [comment]
Hey, @schirrel  sir, I am very beginner in coding I also cant assure you that I can solve this issue for you but I want to try to solve the issue I just know little JavaScript and just learned Git and Github.
I'm interested in solving this issue can you please tell me what should I have to do to solve this

**Comment by schirrel** [comment]
hi @Aniruddha-Shriwant of course, i would be glad if you solve this.
Basicaly you have to copy this file
https://github.com/schirrel/node-simple-skeleton/blob/master/src/database/models/Base.js

**Comment by Aniruddha-Shriwant** [comment]
Hey @schirrel  really thanks, that you have shown trust on me
I will solve this problem 
so basically I will copy this file: https://github.com/schirrel/node-simple-skeleton/blob/master/src/database/models/Base.js
and paste it as a new file, named as "Base.js" in here: https://github.com/schirrel/pg-connection/tree/main/Base 
Is this the tasks you want me to do?

**Comment by Aniruddha-Shriwant** [comment]
Or should I Copy it and edit your index.js file from here https://github.com/schirrel/pg-connection/tree/main/Base

**Comment by schirrel** [comment]
You're right. Woukd bem better copy in index.js

Em seg, 7 de set de 2020 22:20, Aniruddha Shriwant <notifications@github.com>
escreveu:

**Comment by Aniruddha-Shriwant** [comment]
Ohk I had done that 
Let me now give PR
