### ISSUE TITLE
Config and Utils

### ISSUE THREAD

**Issue by schirrel** [schirrel/pg-connection#4]
Create the config file based on https://github.com/schirrel/node-simple-skeleton/blob/master/src/database/Database.js

and Utils/QueryBuilder based on https://github.com/schirrel/node-simple-skeleton/blob/master/src/database/QueryBuilder.js

**Comment by Aniruddha-Shriwant** [comment]
Hey, @schirrel  do I need to copy this https://github.com/schirrel/node-simple-skeleton/blob/master/src/database/QueryBuilder.js
and paste it in your https://github.com/schirrel/pg-connection/tree/main/Config as index.js ?
